### ISSUE TITLE
Advancements firework config don't take in account advancements from different mods beside ender core/io and vanilla

### ISSUE THREAD

**Issue by mser7** [SleepyTrousers/EnderCore#100]

**Comment by tterrag1098** [comment]
That's not possible, it just responds to ANY `AdvancementEvent`, there are zero checks for specific advancements.

**Comment by mser7** [comment]
Forgive me, the advancement I got is the meteor mining one, which require you to mine inside a meteor, and that is what disable the fireworks :(
