### ISSUE TITLE
mysticalagriculture:tier1_inferium_seeds

### ISSUE THREAD

**Issue by Thetoastbrotcraft** [SleepyTrousers/EnderCore#104]
In the crash report, stands that the mysticalagriculture: tier1_inferium_seeds is a problem. Thus is The Crash-Report :
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  IC2core (industrialcraft-2-2.6.15-ex110.jar)
  LittlePatchingLoader (LittleTiles+v1.4.12+mc1.10.2.jar)
  MovingWorldCoreMod (MovingWorld-Mod-1.10.2.jar)
  MalisisCorePlugin (MalisisCore-1.10.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  CreativePatchingLoader (CreativeCore+v1.7.3+mc1.10.2.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  OpenEyePlugin (OpenEye.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.7.3.224.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.19.jar)
  MalisisSwitchesPlugin (MalisisSwitches-Mod-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/11/19 9:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderCore (endercore)
Caused by: java.lang.IllegalArgumentException: mysticalagriculture:tier1_inferium_seeds is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)
	at com.enderio.core.common.util.ItemUtil.parseStringIntoRecipeItem(ItemUtil.java:107)
	at com.enderio.core.common.util.ItemUtil.parseStringIntoItemStack(ItemUtil.java:167)
	at com.enderio.core.common.handlers.RightClickCropHandler$PlantInfo.init(RightClickCropHandler.java:44)
	at com.enderio.core.common.config.ConfigHandler.loadRightClickCrops(ConfigHandler.java:192)
	at com.enderio.core.EnderCore.postInit(EnderCore.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2714769912 bytes (2589 MB) / 5066719232 bytes (4832 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJ	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJ	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJ	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJ	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJ	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJ	OpenComputers|Core{1.7.3.224} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJ	OpenEye{0.8} [OpenEye] (OpenEye.jar) 
	UCHIJ	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJ	libVulpes{0.2.6.} [libVulpes] (LibVulpes-1.10.2.jar) 
	UCHIJ	advancedRocketry{1.0.19} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.19.jar) 
	UCHIJ	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJ	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	UCHIJ	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJ	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
	UCHIJ	ctm{MC1.10.2-0.3.2.35} [CTM] (CTM-MC1.10.2-0.3.2.35.jar) 
	UCHIJ	chisel{MC1.10.2-0.2.1.47} [Chisel] (Chisel-MC1.10.2-0.2.1.47.jar) 
	UCHIJ	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJ	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJ	chiselsandbits{12.18} [Chisels & Bits] (chiselsandbits-12.18.jar) 
	UCHIJ	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJ	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UCHIE	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIE	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UCHIJ	compatlayer{0.3.1} [compatlayer] (compatlayer-1.10-0.3.1.jar) 
	UCHIJ	creativecore{1.7.4} [CreativeCore] (CreativeCore+v1.7.3+mc1.10.2.jar) 
	UCHIJ	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIE	cyberware{beta-0.2.10} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.10.jar) 
	UCHIJ	movingworld{1.10.2-0007} [Moving World] (MovingWorld-Mod-1.10.2.jar) 
	UCHIJ	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (Davincis-Vessels-Mod-1.10.2.jar) 
	UCHIJ	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.5.2_1.10.2.jar) 
	UCHIJ	props{2.5.2} [Decocraft] (Decocraft-2.5.2_1.10.2.jar) 
	UCHIJ	extracells{1.10.2-2.4.4a15} [Extra Cells 2] (ExtraCells-1.10.2-2.4.4a15.jar) 
	UCHIJ	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.9.8.jar) 
	UCHIJ	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJ	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJ	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJ	fw{1.5.1} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.1.jar) 
	UCHIJ	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCHIJ	gravitygun{6.0.1} [GravityGun] (GravityGun-1.10.2-6.0.1.jar) 
	UCHIJ	harvestcraft{1.10.2j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.10.2.jar) 
	UCHIJ	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJ	trackapi{1.1} [Track API] (TrackAPI-1.1_1.10.jar) 
	UCHIJ	immersiverailroading{1.5.0} [Immersive Railroading] (ImmersiveRailroading-1.5.0_1.10-43.jar) 
	UCHIJ	IC2{2.6.15-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.15-ex110.jar) 
	UCHIJ	industrialwires{1.4-18} [Industrial Wires] (IndustrialWires-1.4-18.jar) 
	UCHIJ	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJ	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJ	littletiles{1.4.8} [LittleTiles] (LittleTiles+v1.4.12+mc1.10.2.jar) 
	UCHIJ	malisiscore{1.10.2-4.4.0} [MalisisCore] (MalisisCore-1.10.2.jar) 
	UCHIJ	malisisblocks{1.10.2-4.2.0} [Malisis Blocks] (MalisisBlocks-Mod-1.10.2.jar) 
	UCHIJ	malisisdoors{1.10.2-5.1.8} [MalisisDoors] (MalisisDoors-Mod-1.10.2.jar) 
	UCHIJ	malisisswitches{1.10.2-3.1.0} [Malisis Switches] (MalisisSwitches-Mod-1.10.2.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.10.2.jar) 
	UCHIJ	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCHIJ	OpenComputers{1.7.3.224} [OpenComputers] (OpenComputers-MC1.10.2-1.7.3.224.jar) 
	UCHIJ	portalgun{6.0.1} [PortalGun] (PortalGun-1.10.2-6.0.1.jar) 
	UCHIJ	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UCHIJ	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJ	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJ	projectred-fabrication{4.8.4.49} [ProjectRed Fabrication] (ProjectRed-1.10.2-4.8.4.49-fabrication.jar) 
	UCHIJ	projectred-illumination{4.8.4.49} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.4.49-lighting.jar) 
	UCHIJ	roads{1.2.1} [Roads Mod] (roads-1.2.1-de.jar) 
	UCHIJ	srsm{1.10.2-1.0.5.1} [Saracalia's Random Stuff Mod] (SRSM-1.10.2-1.0.5.1.jar) 
	UCHIJ	thutcore{3.21.0} [Thut Core] (thutcore-3.21.0.jar) 
	UCHIJ	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.13.jar) 
	UCHIJ	bspkrsCore{at_0.9} [bspkrsCore] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJ	Treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJ	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJ	wrcbe{2.0.0} [WirelessRedstone-CBE] (WR-CBE-1.10.2-2.0.0.18-universal.jar) 
	Loaded coremods (and transformers): 
CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  
IC2core (industrialcraft-2-2.6.15-ex110.jar)
  
LittlePatchingLoader (LittleTiles+v1.4.12+mc1.10.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
MovingWorldCoreMod (MovingWorld-Mod-1.10.2.jar)
  
MalisisCorePlugin (MalisisCore-1.10.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CreativePatchingLoader (CreativeCore+v1.7.3+mc1.10.2.jar)
  
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
OpenEyePlugin (OpenEye.jar)
  openeye.asm.MultiTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.7.3.224.jar)
  li.cil.oc.common.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.19.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MalisisSwitchesPlugin (MalisisSwitches-Mod-1.10.2.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4534' Renderer: 'Intel(R) HD Graphics 620'
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-61.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/cyberware-1.9.4-1.10.2-beta-0.2.10.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-61.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/cyberware-1.9.4-1.10.2-beta-0.2.10.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/cyberware-1.9.4-1.10.2-beta-0.2.10.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/cyberware-1.9.4-1.10.2-beta-0.2.10.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-61.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-61.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Frank_Privat/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-61.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RF:OFF, RFItem:OFF, Waila:OFF, JEI:ON, THE_ONE_PROBE:OFF

**Comment by Tfarcenim** [comment]
What

**Comment by big-lip-bob** [comment]
Frist off all, How is this related to EnderIO, Second Where's the crashlog so more advanced peopke can read and interpret it, Third, read the form. REEEEEEE

**Comment by tyler489** [comment]
I'm going to guess that you have mystical agriculture installed... but I'm not digging through that wall of text if it's not on pastebin or simular. Do you have any other mods that modify the way mystical agriculture work?

Or did you change the endercore config file?

**Comment by HenryLoenwind** [comment]
Don't use config files of Endercore for Minecraft 1.12.2 with Endercore for Minecraft 1.10.2.

**Comment by Thetoastbrotcraft** [comment]
How can I change this?

**Comment by tterrag1098** [comment]
Delete your config file and regenerate it.
