### ISSUE TITLE
[FIXED] [CLOSED]Endercore 1.7.10 Crash

### ISSUE THREAD

**Issue by policeMarcus** [SleepyTrousers/EnderCore#108]
Crash when loading it, I have been reading many issues like this but the contributor just puts invalid on them and doesn't say how to fix it. So it is basically the beetroot error, I saw that I should delete or change the harvest config, But it exists literally 500 configs in the zip file. So if anyone would be kind to guide me on what files I should click on

![thacode](https://user-images.githubusercontent.com/45606230/57325703-f1b08580-710a-11e9-84e7-8198bd5fa398.png)

**Comment by HenryLoenwind** [comment]
1. Open your minecraft folder
2. Go to the "config" subfolder
3. Got to the "endercore" subfolder
4. Delete the file "cropconfig.json"

Again, this is not us using a time machine to ship a cureent file in a 2016 release, this is **you** using a config file from a Minecraft 1.12 (or 1.11, 1.10 or 1.9) installation in a 1.7.10 installation.

**Comment by policeMarcus** [comment]
Uh, No. Not my fault, I just downloaded the mods and now I have 1.12 installations in my 1.7.10 installations? No good.
