### ISSUE TITLE
My server has crashed

### ISSUE THREAD

**Issue by 3269199948** [SleepyTrousers/EnderCore#110]
[crash-2019-05-23_12.39.25-server.txt](https://github.com/SleepyTrousers/EnderCore/files/3211825/crash-2019-05-23_12.39.25-server.txt)

**Comment by SplitInfinitive** [comment]
#notEIO #notEnoughInformation #didNotReadInstructions

Edit For Clarity: Don't blindly report to the first core mod in the report.  This isn't an EIO/Ender Core problem so you should probably read the report or google what to look for in one if you don't know how before reporting here.

**Comment by 3269199948** [comment]
> #notEIO #notEnoughInformation #didNotReadInstructions

I don't understand what you are saying.

**Comment by tyler489** [comment]
This is not an endercore issue please repost it here https://github.com/EleC0TroN/EndRebornII
