### ISSUE TITLE
crash while playing 

### ISSUE THREAD

**Issue by thekiller81** [SleepyTrousers/EnderCore#111]
i am new to this game,

here the crash report. pls help.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 6/23/19 3:28 AM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at mrriegel.playerstorage.ExInventory$Handler.refresh(ExInventory.java:685)
	at mrriegel.playerstorage.ExInventory$Handler.getSlots(ExInventory.java:694)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:147)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:67)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at mrriegel.playerstorage.ExInventory$Handler.refresh(ExInventory.java:685)
	at mrriegel.playerstorage.ExInventory$Handler.getSlots(ExInventory.java:694)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:147)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:67)

-- Block entity being ticked --
Details:
	Name: xu2:tiletransferholder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
	Block type: ID #429 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder // extrautils2:transferholder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-240,60,163), Chunk: (at 0,3,3 in -15,10; contains blocks -240,0,160 to -225,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #429 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder // extrautils2:transferholder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Best World
	All players: 1 total; [EntityPlayerMP['thekiller81'/619185, l='Best World', x=-208.26, y=78.00, z=233.04]]
	Chunk stats: ServerChunkCache: 385 Drop: 0
	Level seed: -6330248713461894740
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":7,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":7,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":4,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":20,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":20,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":15,"goldCount":15,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":13,"redstoneCount":13,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":20,"diamondCount":20,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":10,"lapisCount":10,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (-256,64,168), Chunk: (at 0,4,8 in -16,10; contains blocks -256,0,160 to -241,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3832295 game time, 1290001 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100365 (now: false), thunder time: 143536 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 896108880 bytes (854 MB) / 2590818304 bytes (2470 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | actuallyadditions                 | 1.12.2-r142       | ActuallyAdditions-1.12.2-r142.jar               | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | thedragonlib                      | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                   | None                                     |
	| LCHIJA | armorplus                         | 1.12.2-11.13.0.40 | armorplus-1.12.2-11.13.0.40.jar                 | None                                     |
	| LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2439        | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar   | None                                     |
	| LCHIJA | bonsaitrees                       | 1.1.1             | bonsaitrees-1.1.1-b138.jar                      | None                                     |
	| LCHIJA | bookshelf                         | 2.3.559           | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| LCHIJA | cofhworld                         | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | crafttweaker                      | 4.1.18            | CraftTweaker2-1.12-4.1.18.jar                   | None                                     |
	| LCHIJA | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.18.jar                   | None                                     |
	| LCHIJA | jei                               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| LCHIJA | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.18.jar                   | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.57     | EnderCore-1.12.2-0.5.57.jar                     | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | p455w0rdslib                      | 2.1.44            | p455w0rdslib-1.12.2-2.1.44.jar                  | None                                     |
	| LCHIJA | theoneprobe                       | 1.4.21            | theoneprobe-1.12-1.4.21.jar                     | None                                     |
	| LCHIJA | danknull                          | 1.4.46            | DankNull-1.12-1.4.46.jar                        | None                                     |
	| LCHIJA | dynamictrees                      | 1.12.2-0.9.5      | DynamicTrees-1.12.2-0.9.5.jar                   | None                                     |
	| LCHIJA | dynamictreesbop                   | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar               | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderiobase                       | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | ftblib                            | 5.4.3.103         | FTBLib-5.4.3.103.jar                            | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                       | None                                     |
	| LCHIJA | silentlib                         | 3.0.13            | SilentLib-1.12.2-3.0.13+167.jar                 | None                                     |
	| LCHIJA | extendeddays                      | 0.2.9             | ExtendedDays-1.12.2-0.2.9-28.jar                | None                                     |
	| LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| LCHIJA | fasterladderclimbing              | 0.1-146           | FasterLadderClimbing-1.12-0.1-146.jar           | None                                     |
	| LCHIJA | findyourway                       | 1.2.1             | findyourway-1.12.2-1.2.1.jar                    | None                                     |
	| LCHIJA | gottschcore                       | 1.7.0             | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar   | None                                     |
	| LCHIJA | gyth                              | 2.1.35            | Gyth-1.12.2-2.1.35.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ironbackpacks                     | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.64.843 | ironchest-1.12.2-7.0.64.843.jar                 | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | jaff                              | 1.7_for_1.12      | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
	| LCHIJA | limelib                           | 1.7.10            | limelib-1.12.2-1.7.10.jar                       | None                                     |
	| LCHIJA | radixcore                         | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| LCHIJA | mca                               | 1.12.2-5.3.1      | MCA-1.12.x-5.3.1-universal.jar                  | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.5.3             | mcjtylib-1.12-3.5.3.jar                         | None                                     |
	| LCHIJA | meecreeps                         | 1.3.1             | meecreeps-1.12-1.3.1.jar                        | None                                     |
	| LCHIJA | minions                           | 2.0.2             | Minions-1.12.jar                                | None                                     |
	| LCHIJA | multimob                          | 1.0.5             | multimob-1.0.5.jar                              | None                                     |
	| LCHIJA | natura                            | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                      | None                                     |
	| LCHIJA | playerstorage                     | 1.2.7             | playerstorage-1.12.2-1.2.7.jar                  | None                                     |
	| LCHIJA | primitivemobs                     | 1.2.3a            | primitivemobs-1.2.3a.jar                        | None                                     |
	| LCHIJA | simpledivegear                    | 1.0.3             | SimpleDivingGear-1.0.3+mc+1.12.2.jar            | None                                     |
	| LCHIJA | storagenetwork                    | 1.7.7             | SimpleStorageNetwork-1.12.2-1.7.7.jar           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | storagedrawers                    | 1.12-5.2.5        | StorageDrawers-1.12.2-5.3.4.jar                 | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinymobfarm                       | 1.0.5             | TinyMobFarm-1.12.2-1.0.5.jar                    | None                                     |
	| LCHIJA | toolbelt                          | 1.7.1             | ToolBelt-1.12.0-1.7.1.jar                       | None                                     |
	| LCHIJA | tc                                | 1.1               | ToolsCombine[1.12.2].jar                        | None                                     |
	| LCHIJA | treasure2                         | 1.3.0             | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar     | None                                     |
	| LCHIJA | xat                               | 0.25.1            | Trinkets+and+Baubles-1.12.2-0.25.1.jar          | None                                     |
	| LCHIJA | undergroundbiomes                 | 1.3.2             | UndergroundBiomesConstructs-1.12-1.3.2.jar      | None                                     |
	| LCHIJA | vanilladeathchest                 | 1.12.2-1.3.0.0    | vanilladeathchest-1.12.2-1.3.0.0.jar            | None                                     |
	| LCHIJA | wanionlib                         | 1.12.2-2.2        | WanionLib-1.12.2-2.2.jar                        | None                                     |
	| LCHIJA | xray                              | 1.4.0             | xray-1.12.2-1.4.0.jar                           | None                                     |
	| LCHIJA | yabba                             | 1.1.2.52          | YABBA-1.1.2.52.jar                              | None                                     |
	| LCHIJA | minersadvantage                   | 1.3.15.191        | MinersAdvantage-1.12.2-1.3.15.192.jar           | None                                     |
	| LCHIJA | unidict                           | 1.12.2-2.9.2      | UniDict-1.12.2-2.9.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['thekiller81'/619185, l='Best World', x=-208.26, y=78.00, z=233.04]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by big-lip-bob** [comment]
-- Block entity being ticked --
Details:
Name: xu2:tiletransferholder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
Block type: ID #429 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder // extrautils2:transferholder)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (-240,60,163), Chunk: (at 0,3,3 in -15,10; contains blocks -240,0,160 to -225,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Actual block type: ID #429 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder // extrautils2:transferholder)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1835)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

ExtraUtils 2 fault, what did you do before the crash, it would help more, it seeems totally unrelated to EnderIO

**Comment by CitiesXL2815** [comment]
send crash ExtraUtils 2 @HenryLoenwind close this issue it's a bug in another software not enderio

**Comment by HenryLoenwind** [comment]
Either ExtraUtils2 or whatever `mrriegel.playerstorage` is. I'd go for the latter first.

**Comment by thekiller81** [comment]
what i need to do ??

**Comment by thekiller81** [comment]
oic, ok i still learning, even to post this is hard for me. do i need to remove enderio, Extrautils2 or player storage ( i love all of it ). what i need to do

**Comment by thekiller81** [comment]
now i have bigger problem

Internal exception java lang illegalargumentexception payload may not be larger than 32767 bytes

this is making me cry
