### ISSUE TITLE
Ender Core not updated for Ender IO

### ISSUE THREAD

**Issue by TheSexyYeti** [SleepyTrousers/EnderCore#113]
I don't know if something was changed or updated. But when I try to load my game. It stops and gives me a messages saying 

"You must include the right dependencies for the following mods:
Ender IO:
Requires Ender Core 1.12.2 - 0.5.65 or above (You have 1.12.2 - 0.5.59)"

I've updated Ender Core through the Twitch/Curse Launcher as far as their file go. Just wanted to give you a heads up.

**Comment by SplitInfinitive** [comment]
in your twitch launcher go into your modpack profile settings and change preferred version to "alpha", that version is the one it's asking for but by default Twitch will only download "release" versions.  This is probably an unintentional thing but that'll work around your issue for the time being.

**Comment by tyler489** [comment]
🤦‍♂ Hey @HenryLoenwind Can You fix that

**Comment by HenryLoenwind** [comment]
done
