### ISSUE TITLE
The ender io files multiply and don't let me start the custom modpack.

### ISSUE THREAD

**Issue by Jucatorul31** [SleepyTrousers/EnderCore#120]
![Capture](https://user-images.githubusercontent.com/67744220/86361626-ca0c6d00-bc7c-11ea-9855-22de53494cda.PNG)

**Comment by VT-14** [comment]
I believe you have both the "Monolithic" version and the piecemeal versions installed at the same time.  As the warnings in the CurseForge description clearly state, installing both causes this duplication issue because you literally installed duplicates.
