### ISSUE TITLE
Can't get EnderCore 1.12 to run in eclipse dev env

### ISSUE THREAD

**Issue by okidor** [SleepyTrousers/EnderCore#121]
Hello,

I tried to import EnderCore (branch 1.12) with the following steps:
- executed "eclipse" gradle task
- right click on the generated file EnderCore_Client.launch -> run as EnderCore_Client (The RunClient task does not work)

Weirdly, there is no "genEclipseRuns" gradle task although there is a "genIntellijRuns" task.

The game begins to load but then crash with the following error:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderCore (endercore)
Caused by: java.lang.IllegalStateException: EnderCorePlugin accessed too early!

full trace:
[latest.log](https://github.com/SleepyTrousers/EnderCore/files/4904736/latest.log)

Am i doing something wrong with the build steps ?

Please, note that if i try to run EnderCore from the 1.13 branch which has a "genEclipseRuns" task, the game runs properly.

**Comment by HenryLoenwind** [comment]
I've never run endercore on itself, but you are probably missing the `-Dfml.coreMods.load=com.enderio.core.common.transform.EnderCorePlugin` argument to load the coremod. (run config>arguments>vm arguments)

**Comment by okidor** [comment]
That has indeed worked, thank you.
