### ISSUE TITLE
Crash with latest sound filters

### ISSUE THREAD

**Issue by mxnmnm** [SleepyTrousers/EnderCore#122]
I updated sound filters and I got a crash when I entered my world blaming this mod for stuff so if the report belongs over there let me know. If you need more info let me know.

https://gist.github.com/mxnmnm/b77e4a854e56af8ca6d34f32f3ed82ea

**Comment by mxnmnm** [comment]
This seems to happen when trying to enter existing worlds so it isn't as bad of an issue as I originally thought

**Comment by mxnmnm** [comment]
I also can't recreate it so not sure what's going on here

**Comment by HenryLoenwind** [comment]
#107
