### ISSUE TITLE
Major Vulnerability

### ISSUE THREAD

**Issue by RealmKebab** [SleepyTrousers/EnderCore#142]
Your mod has a vulnerability, it affects versions 1.9-1.13.2 (according to serialization is bad), because your mod is popular, people may download your mod without notice
this is a huge major vulnerability. I advise you fix it immediately
https://github.com/dogboy21/serializationisbad
https://blog.mmpa.info/posts/bleeding-pipe/

**Comment by tyler489** [comment]
I would advise you to check the last patch https://github.com/SleepyTrousers/EnderCore/commit/76170fc31be2aff3798ccf04fb51820eaef5abe8

**Comment by RealmKebab** [comment]
> I would advise you to check the last patch [76170fc](https://github.com/SleepyTrousers/EnderCore/commit/76170fc31be2aff3798ccf04fb51820eaef5abe8)

ah alright,
i got confused on why the guy was spamming pull requests lol
