### ISSUE TITLE
[Question] Forge compatible versions 

### ISSUE THREAD

**Issue by accessdenied0** [SleepyTrousers/EnderCore#18]
Dear EnderCore-Team (tag @tterrag1098 ),

I got a question about the compatible version of Forge for your mod. I use the version 10.13.4.1448 and it works fine, but a mod I want to use uses the Forge version 10.13.4.1492. It seems to be the issue here that the newest EnderCore doesn't work on Forge 10.13.4.1448 (stable), only on 10.13.4.1490 +.

Is the version 10.13.4.1492 now stable enough and/or do I need this version of Forge for future use?

https://github.com/HenryLoenwind/EnderIOAddons/issues/1#issuecomment-141781800

I hope you guys can help here a bit,

access_denied

**Comment by tterrag1098** [comment]
What do you mean "doesn't work" on 1448? Do you have a crash log?
