### ISSUE TITLE
EnderCore refuses to load with ttCore; Mods that require ttCore refuse to load without ttCore.

### ISSUE THREAD

**Issue by nullifiedcat** [SleepyTrousers/EnderCore#2]
Can you please do something about it? Mods that require ttCore like RedstoneArmory cannot load with new EnderIO

**Comment by tterrag1098** [comment]
There is a reason EnderCore is not released yet. Over time these mods will be ported to use EnderCore and this issue will no longer exist, but there are many reasons why they cannot load at the same time. Unfortunately for now this is how it must be.

**Comment by KaneHart** [comment]
Just to add to this that Tech has updated RA to use the latest EnderCore.. It's marked Alpha if I recalled but might be bring more people to the yard.
