### ISSUE TITLE
Matter Overdrive in-game config gui doesn't open

### ISSUE THREAD

**Issue by Alaberti** [SleepyTrousers/EnderCore#27]
Referenced here originally: https://github.com/simeonradivoev/MatterOverdrive/issues/316

EDIT - EnderCore 0.2.0.30_beta, Forge 1517, Matter Overdrive 0.4.0 dev 159

When I try to open the config in game, I get this error in the console log:

[B#328] [15:10:40] [Client thread/ERROR] [FML]: There was a critical issue trying to build the config GUI for mo
[B#328] java.lang.NoSuchMethodException: matteroverdrive.gui.GuiConfig.(net.minecraft.client.gui.GuiScreen)
[B#328] at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_60]
[B#328] at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_60]
[B#328] at cpw.mods.fml.client.GuiModList.func_146284_a(GuiModList.java:121) [GuiModList.class:?]
[B#328] at com.enderio.core.client.gui.bettermodlist.GuiEnhancedModList.func_146284_a(GuiEnhancedModList.java:271) [GuiEnhancedModList.class:?]
[B#328] at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
[B#328] at com.enderio.core.client.gui.bettermodlist.GuiEnhancedModList.func_73864_a(GuiEnhancedModList.java:216) [GuiEnhancedModList.class:?]
[B#328] at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
[B#328] at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
[B#328] at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
[B#328] at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
[B#328] at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
[B#328] at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328] at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#328] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by tterrag1098** [comment]
EnderCore replaces the mod list GUI but it is not the cause of this crash. In fact this stacktrace doesn't make much sense. I suggest you report this to Matter Overdrive.
