### ISSUE TITLE
Newest version prevent MC starting

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderCore#3]
Newest version prevents MC from starting with a crash: http://hastebin.com/kepawefuxo.vala

**Comment by MatthiasMann** [comment]
Somehow you managed to download an intermediate version of EnderCore 1.7_alpha which was only available for 30 minutes :/ Download the latest EnderCore version again.

**Comment by Unrepentant-Atheist** [comment]
Yea, that solved it. Thanks!
