### ISSUE TITLE
NPE with pick block

### ISSUE THREAD

**Issue by spannerman79** [SleepyTrousers/EnderCore#39]
OpenEye Report: http://openeye.openmods.info/crashes/87a261e5123407e39b8a0846bdeeadf3

To replicate:
pick block reinforced obsidian while in creative - client crash.

[crash-2016-04-25_03.25.38-client.txt](https://github.com/SleepyTrousers/EnderCore/files/233566/crash-2016-04-25_03.25.38-client.txt)

**Comment by HenryLoenwind** [comment]
PS: "Duplicate" as in already reported and handled ( #38 ), not as in "there's another issue for it".
