### ISSUE TITLE
[1.9.4] Auto Smelt on armor

### ISSUE THREAD

**Issue by tommyTT** [SleepyTrousers/EnderCore#42]
In the end city loot chests I found a few diamond helmets that had the auto smelt enchantment on it. If I try to enchant my armor, this enchantment also comes up. Putting it on armor with an enchanted book also works. All of this shouldn't be possible.

Minecraft Version 1.9.4
Forge Version 12.17.0.1936
EnderCore Version 0.4.0.21-alpha

**Comment by foxanthony1** [comment]
XP Boost is also showing up for armor enchants.
