### ISSUE TITLE
[1.9.4] EnderCore incompatible with SpongeForge

### ISSUE THREAD

**Issue by Mohron** [SleepyTrousers/EnderCore#44]
I love EnderIO but server plugins are also a must. I know both sponge and EnderCore for 1.9.4 are in alpha/beta but I thought I should at least bring it to your attention. Hope it can be fixed without too much trouble.

Mod Versions
EnderCore-1.9.4-0.4.0.23-alpha.jar
spongeforge-1.9.4-1954-5.0.0-BETA-1417.jar

[Crash Report](http://pastebin.com/xrrtiB9U)

**Comment by tterrag1098** [comment]
#37
