### ISSUE TITLE
[1.9.4] XP dupe maybe?

### ISSUE THREAD

**Issue by G-Stav** [SleepyTrousers/EnderCore#46]
I have XP Boost III on a Silk touch pick and it's giving me XP when mining nether quartz. Going to try with other ores as soon as I can, but I think this might be related to the XP Boost enchant since I haven't had issues with it since I added it to the pick.

**Comment by HenryLoenwind** [comment]
Um, so what's your issues here?

**Comment by G-Stav** [comment]
So I tried it with a new diamond pick, and it works on all the vanilla ore. It gives you XP dispite using silktouch. So basically you can mine the same or over and over again for free XP.
