### ISSUE TITLE
gunPowder is being registered as "dustGunpowder" in the OreDict

### ISSUE THREAD

**Issue by mezz** [SleepyTrousers/EnderCore#47]
EnderCore is giving gunpowder the oredict name "dustGunpowder"
https://github.com/SleepyTrousers/EnderCore/blob/master/src/main/java/com/enderio/core/common/OreDict.java#L31

This breaks some expectations about dusts, which are generally crushed up metal ingots. As far as I can tell nothing is using it, and gunpowder already has the oreDict name "gunpowder" give by Forge.
This causes gunpowder to be picked up by Forestry's Miner's backpack, when it belongs in the Hunter's backpack.

**Comment by tterrag1098** [comment]
Looks like we have @Jaredlll08 to thank for this one https://github.com/tterrag1098/ttCore/commit/7643b894cebf41488a922c081b537ae0c1c6c6a2

I'm not sure why it was added if it already had a name. Or was that forge oredict added since 2014...

**Comment by mezz** [comment]
Forge added more oredict names recently:
https://github.com/MinecraftForge/MinecraftForge/commit/d31cf8ddbc52c9d5d9792762fd7d06a756848ff3

**Comment by jaredlll08** [comment]
Uh what, it is a dust...
I'm fairly sure the Forge oredict was added later anyway.

**Comment by mezz** [comment]
Yes it is a dust irl, but it is not a dust according to oredict convention. There is no gunpowder ingot, or other gunpowder non-dust version.

**Comment by jaredlll08** [comment]
For now!

mkdir GPiAD; gradle setupDecompWorkspace idea

Though seriously, I prefer dustGunpowder, makes it easier to oredict all
dusts
On Jun 20, 2016 12:17 AM, "mezz" <notifications@github.com> wrote:

Yes it is a dust irl, but it is not a dust according to oredict convention.
There is no gunpowder ingot, or other gunpowder non-dust version.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SleepyTrousers/EnderCore/issues/47#issuecomment-227023792>,
or mute the thread
<https://github.com/notifications/unsubscribe/AFS9xeTlmbfJEIVnRl3jkIoLA1wG1CBqks5qNb_7gaJpZM4I5Qw0>
.

**Comment by tterrag1098** [comment]
I am on @jaredlll08's side here, you could argue "convention" all day but you are relying on undefined semantics. However, since it is a dupe registration we will remove it (1.9 only)

**Comment by mezz** [comment]
Similar issue with `blockObsidian`, Forge registers it as `obsidian`.
I'd agree here that `blockObsidian` is better but it's still a duplicate :/

**Comment by tterrag1098** [comment]
@mezz One thing I noticed is that forge registers redstone as dustRedstone. So this already contradicts your convention, even though it works out in the end as redstone does belong in the miner's backpack. Either way as I said, we will be removing the duplicate.

**Comment by mezz** [comment]
Having it mostly correct is good enough for me. I'll probably have to make a blacklist at some point. I'm basing my ideas off of an oredictionary dump of a large kitchen sink pack on 1.7.10. https://gist.github.com/mezz/cf5d1a055e0c7fdb6cab

**Comment by AnrDaemon** [comment]
Having items/blocks registered in multiple oredicts is not a bug per se.
Imagine Thaumcraft using 'parafernalia' oredict and adding to it everything that can be used as infusion stabilizer.
The problem, however, is an inconsistent oredict usage. And 'obsidian' is a good example of the latter.
