### ISSUE TITLE
EnderCore + AoA

### ISSUE THREAD

**Issue by AstroCat2Space** [SleepyTrousers/EnderCore#49]
So, for some reason any bow from the Advent of Ascension mod will not shoot Holly Arrows unless a vanilla arrow is in my inventory, and I found out the EnderCore mod causes this.

Minecraft 1.7.10
Forge 10.13.4.1614
EnderCore 1.7.10-0.2.0.36_beta

**Comment by CrazyPants** [comment]
Try disabling the infinity bow tweak in the config file
B:infinibow=false

**Comment by AstroCat2Space** [comment]
It worked. Thanks!
