### ISSUE TITLE
[1.10.2] Server crash  on startup (java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiRepair)

### ISSUE THREAD

**Issue by cheriekeks** [SleepyTrousers/EnderCore#50]
Updated from EnderCore-1.10-0.4.0.33-alpha

crashes server on startup, works fine on client side

[crash-2016-07-08_14.10.32-server.txt](https://github.com/SleepyTrousers/EnderCore/files/354177/crash-2016-07-08_14.10.32-server.txt)

**Comment by HenryLoenwind** [comment]
thx, new build is on its way
