### ISSUE TITLE
1.10.2 cropConfig being completely ignored

### ISSUE THREAD

**Issue by MysticAura** [SleepyTrousers/EnderCore#54]
MC Version: 1.10.2
Forge Version: 2043
Core Mod Version: 1.10.2-0.4.1.44-beta
Mod Version: 1.10.2-3.0.1.77-beta

Farming station refuses to right click any crops. Even when I test with just the default cropConfig.json. file it smacks wheat like there's no right click option.

**Comment by tterrag1098** [comment]
cropConfig has nothing to do with the farming station

**Comment by MysticAura** [comment]
So..the mod is aware of right click crops, but the farming station ignores the functionality. Now I'm just confused and disappointed. Closing the issue I guess

**Comment by tterrag1098** [comment]
I don't really see how the farming station behaving differently would be of
any advantage. Just because it doesn't need to replant the seed?

**Comment by HenryLoenwind** [comment]
btw, the "not replanting the moment it harvests" is a bug which will be fixed
