### ISSUE TITLE
EnderCore crashes dev environment

### ISSUE THREAD

**Issue by thebrightspark** [SleepyTrousers/EnderCore#55]
I had originally posted on the Minecraft Forums about this, thinking I had done something wrong, however someone else (Choonster) informed me it was probably a Forge issue. However, LexManos said that it was infact the mod's fault. I don't know what, but that's what I know.

Details I have in the original thread here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2719254-issue-with-optional-mod-dependency

And the Forge bug report was posted and replied to by LexManos here:
http://www.minecraftforge.net/forum/index.php/topic,41026.0.html

I originally tested in 1.9.4 with EnderCore 0.4.0.26-alpha and have then tested in 1.10.2 with EnderCore 0.4.1.46-beta. I do also have EnderIO and JEI in the environment too, but I presume they won't affect the outcome.

**Comment by thebrightspark** [comment]
Sorry, I just noticed this had been reported before (https://github.com/SleepyTrousers/EnderCore/issues/48), however it hadn't been resolved. Also I'm using IntelliJ Idea as my IDE.

**Comment by HenryLoenwind** [comment]
LexManos is an asshole who doesn't know what he's talking about.

**Comment by HenryLoenwind** [comment]
As you have a dev env setup, could you compile a custom version of endercore and try that one?

That would be without this commit: https://github.com/SleepyTrousers/EnderCore/commit/81b86d4d535778e73a39dfe13e3ea26c564293f7 (you can leave the logger change, that is harmless. so it'd just be deleting those 3 annotations)

**Comment by thebrightspark** [comment]
So, I compiled it and it worked. Although EnderIO complained of needing a later version of EnderCore, MC still loaded up fully compared to crashing near the beginning. FYI I actually didn't remove the static block... I forgot to, but the mod still didn't crash!
