### ISSUE TITLE
Open computers and ender core crash

### ISSUE THREAD

**Issue by weeryan17** [SleepyTrousers/EnderCore#56]
Every time i try to open one of the guis I get a crash when i have opencomputers and ender core installed. I am also reporting this to opencomputers in hopes of getting this crash fixed so I can open computers
here's the crash: http://pastebin.com/U5rwE7g6
along with full game log: http://pastebin.com/tA5C6RYy

**Comment by Vexatos** [comment]
You need to update JustEnoughItems.

**Comment by weeryan17** [comment]
I just read the log and it included ender core. I'm not good at reading mod error reports
