### ISSUE TITLE
[1.7.10] HUD oddity/conflict with DangerRPG

### ISSUE THREAD

**Issue by KryptonCaptain** [SleepyTrousers/EnderCore#66]
I was testing out [DangerRPG](https://minecraft.curseforge.com/projects/dangerrpg) recently, and opened up the player info UI to find this dirt square covering part of the screen. Determined by elimination process that when EnderCore is present, it happens. Without EnderCore, HUD renders as intended. Not really sure why it's causing it, but it does.

![2016-09-15_11 42 25](https://cloud.githubusercontent.com/assets/8790829/18579792/1fb4ed6c-7c3b-11e6-903f-a62063c3e1a6.png)

**Comment by tterrag1098** [comment]
EnderCore version? Minecraft version?

**Comment by KryptonCaptain** [comment]
Oh derp. My bad
EnderCore-1.7.10-0.2.0.38_beta
MC 1.7.10 on forge .1614 (latest)
DangerRPG 1.0.3

**Comment by tterrag1098** [comment]
Fixed and released https://minecraft.curseforge.com/projects/endercore/files/2331048

pending CF approval

**Comment by KryptonCaptain** [comment]
Many thanks!
