### ISSUE TITLE
1.7.10 Forge(custom) + EnderCore + EnderIO

### ISSUE THREAD

**Issue by SvEgiiVEteR** [SleepyTrousers/EnderCore#68]
https://gist.github.com/7e6f85d4341fd448c7a976a16f0f6e62
EnderIO-1.7.10-2.3.0.429_beta.jar
EnderCore-1.7.10-0.2.0.39_beta.jar
I use Forge, took it from my friend(there fix bugs, increase performance )

1)EnderCore-1.7.10-0.2.0.39_beta.jar
with Forge my friend - crash (without EnderIO crash no.)

he did to me 
EnderCore-1.7.10-0.2.0.38_betaFIX.jar
2)the game is not broken, But with EnderCore-1.7.10-0.2.0.38_betaFIX.jar missing common textures on the blocks in the mod EnderIO 

if it is possible to fix сrash, please.

**Comment by HenryLoenwind** [comment]
what?

**Comment by Bogdan-G** [comment]
EnderCore with EIO register empty TechneModel arraylist -> game crash

**Comment by MatthiasMann** [comment]
There will be no support for modified versions of the mod. Also the version for 1.7.10 is no longer under active development.

Try if the crash happens with the latest unmodified versions of EnderIO and EnderCore for 1.7.10 and if yes report it as a new issue.

**Comment by Bogdan-G** [comment]
@MatthiasMann lol, this crash - https://gist.github.com/7e6f85d4341fd448c7a976a16f0f6e62 use official version EnderCore and official version EnderIO.

**Comment by SvEgiiVEteR** [comment]
https://github.com/SleepyTrousers/EnderCore/issues/69
