### ISSUE TITLE
How to change config Endercore on the server 

### ISSUE THREAD

**Issue by vavan0948** [SleepyTrousers/EnderCore#72]
I want  to change infinibow on false In Minecraft client I did this by the options(mods) in Minecraft but how to do this on my server because it didn't have any graphic interface only console pleas help me.
mod version  EnderCore-1.7.10-0.2.0.36_beta

**Comment by HenryLoenwind** [comment]
http://bfy.tw/95Fo

**Comment by vavan0948** [comment]
hmmm... my minecraft server is on windows so you didn't help me. How to change config of your mode on the server

**Comment by AnrDaemon** [comment]
Just like on client. Edit the file in your preferred editor, make changes, save.

**Comment by vavan0948** [comment]
but it's one problem on client I change it in special point in general minecraft menu so I don't know how to change it in editor. Pleas explain me how to do this

**Comment by VT-14** [comment]
There is a config folder in the server files.  Finding Ender Core's config text file(s) is trivial from there.  You can edit them in notepad or any other text editor.  You have to mess with those server files to set up the server, so I assume you know where those are.

If you are asking how to edit the server configs on a server you aren't personally running, then you simply can't.  The Server owner/operator decides what those configs are, and they trump client configs for anything that could affect other players (like needing an arrow or not to use the Infinity Enchantment).

**Comment by vavan0948** [comment]
Thank you very much for your help but I had changed it yet.
