### ISSUE TITLE
Crash at EnderCore loading!

### ISSUE THREAD

**Issue by AchTrindade05** [SleepyTrousers/EnderCore#78]
So I was testing my new Modpack and EnderCore was the first mod I decided to test. In the loading of the mods, in the sixth phase of loading the game crashed. I tested several times: with the version 0.20.39 up to 0.2.0.35 (I know it's an old version already, but wanted to play in the 1.7.10) and the times I tested it always was to crash. I need help! I do not live without ender io (on Minecraft).

-I'm sorry for my English, I'm Brazilian and I don't know how to speak the language well. (I still got the translator's help) :P
Here's the crash report:
[crash-2017-07-12_19.05.46-client.txt](https://github.com/SleepyTrousers/EnderCore/files/1143506/crash-2017-07-12_19.05.46-client.txt)

**Comment by MatthiasMann** [comment]
Your config/enderCore/cropConfig.json is invalid: minecraft:beetroot_seeds doesn't exist in 1.7.10

**Comment by HenryLoenwind** [comment]
PS: Don't use a config file from the 1.10.2 version with 1.7.10.
