### ISSUE TITLE
1.7.10 Crash

### ISSUE THREAD

**Issue by DiabeticDino** [SleepyTrousers/EnderCore#82]
Whenever I try to launch the 1.7.10 version of EnderCore, the game crashes with this message:

The game crashed whilst initializing the game
Error: java.lang.IllegalArgumentException: minecraft:beetroots_seeds is not a
valid string. Strings should be either an oredict name, or in the format object
name;damage (damage is optional)

It only happens for the 1.7.10 version, and doesn't happen without EnderCore.

**Comment by MatthiasMann** [comment]
That's because beetroots are not in 1.7.10 and you are using a endercore config file from 1.10.2.
Either delete that config to get the defautl back - or remove the beetroot entry from the harvesting section.
