### ISSUE TITLE
1.12 MP error when connecting to lan server

### ISSUE THREAD

**Issue by Ezoteric** [SleepyTrousers/EnderCore#88]
So im having this error sometimes when connecting to a friends server he set on lan mode.

22:09:55 | game |   | info | [20:09:55] [Netty Client IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
-- | -- | -- | -- | --
22:09:55 | game |   | info | [20:09:55] [Netty Client IO #1/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler

While we didnt change anything.

I dont have a crash report cause it doesnt crash

PS: this only happend when exiting the server and try to rejoin it.
After both me and my friend relaunch the game it works

**Comment by tyler489** [comment]
Please follow the issue template provided. Also that log doesnt say much. Did u update enderio recently? If so reset your configs

**Comment by HenryLoenwind** [comment]
Tyler, no template here, this is the Endercore repository.

However, this report is completely useless and also completely unrelated to Endercore.

Ezoteric, if I was you, I'd ask someone what an "error message" actually is.
