### ISSUE TITLE
My Ender IO Crashes. Can I please have some assistance?

### ISSUE THREAD

**Issue by ItzGrimmace** [SleepyTrousers/EnderCore#98]
Hi, My MC continuously crashes when I open it. This is the crash report. 

[crash-2018-11-08_18.00.49-client.txt](https://github.com/SleepyTrousers/EnderCore/files/2563964/crash-2018-11-08_18.00.49-client.txt)

If there is anyways to figure out why it crashes, I would be much appreciated, Trying to make a server for my 8 Year Old Niece who just got Minecraft.

**Comment by EpicSquid** [comment]
Remove optifine. Also please use the issue template, it is there for a reason and allows us to more easily help you. This crash log by itself is both difficult to read and not enough information.

**Comment by LumberWizard** [comment]
Please use pastebin or gist for the crashlog, nobody wants to look at it in the issue body.

**Comment by ItzGrimmace** [comment]
Alrighty, where is the issue template, for future reference?

**Comment by EpicSquid** [comment]
Ohhhhh. This is Ender Core's repo. My mistake, the issue template isn't set up here. At the very least, can you let use know what version of Ender IO and Ender Core you have and if you do or don't have optifine installed? Also a pastebin of the crash log would be very helpful.

**Comment by ItzGrimmace** [comment]
I edited it so it's not as jumbled and stuff.

**Comment by ItzGrimmace** [comment]
Like I just did? I'm not sure what that stuff is, this is my first time with this issue.

The version EnderCore is: 1.12.2-0.5.37
The Version EnderIO is: 1.12.2-5.0.37

Yes I have Optifine Installed, Version: 1.13.2_HD_U_E4

**Comment by HenryLoenwind** [comment]
yes, that's an Optifine issue. Also, you're using an ancient version of Forge.

See also http://www.minecraftforge.net/forum/topic/67250-it-looks-like-your-using-an-unsupported-version-of-minecraft-please-help-lol/

**Comment by EpicSquid** [comment]
Well there is your problem. Your using optifine for 1.13.2 of minecraft, but your running minecraft 1.12.2. Try downgrading optifine, or better yet removing it all together. It causes all sorts of visual issues

**Comment by ItzGrimmace** [comment]
Alright, I'll try that.

Also, ancient version of forge? That was the latest Version I was able to find. Is there a newer version?

**Comment by HenryLoenwind** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html

**Comment by ItzGrimmace** [comment]
That is the website I went to and downloaded that verison of forge. Which is the one I'm running off of.

**Comment by HenryLoenwind** [comment]
You are using forge1.12.2-14.23.2.2627 according to your crash report. Your 2627 was published on 03/13/18. The current version is 14.23.5.2768...

**Comment by ItzGrimmace** [comment]
I thought I had installed that one, Weird. I downloaded and installed it after a fresh install of MC and everything else. I will reinstall everything and I'll get back to you.

**Comment by ItzGrimmace** [comment]
Alright, I wanna thank the both of you for helping out. It all works now, Is there a way I can get optifine to work for my server?

**Comment by tterrag1098** [comment]
Optifine is a clientside mod.

**Comment by LumberWizard** [comment]
I'm pretty sure it has server side optimizations too, but I avoid it like the plague so I can't say for sure.
